CREATE DATABASE BRASILEIRAO; 
USE BRASILEIRAO; 
#comandosDDL CRIA;
CREATE TABLE SERIES (
ID INT,
NOME VARCHAR (20),
NUM_PARTIDADAS INT,
TOTAL_GOLS INT,
DESCRICAO VARCHAR (200),
PRIMARY KEY (ID)
);

CREATE TABLE TIMES (
ID INT,
NOME VARCHAR (50),
CIDADE VARCHAR (50),
TECNICO VARCHAR (100),
ESTADIO VARCHAR (50),
FK_SERIES INT,
PRIMARY KEY (ID),
FOREIGN KEY (FK_SERIES) 
REFERENCES SERIES (ID) #referencia de qual tabela vem a chave estrangeira
);

CREATE TABLE JOGADORES (
ID INT,
NOME VARCHAR (100),
NASCIMENTO DATE,
POSICAO VARCHAR (50),
FK_TIMES INT,
PRIMARY KEY (ID),
FOREIGN KEY (FK_TIMES) 
REFERENCES TIMES (ID)
);
#DROP - remover dados permanentemente: comando DROP exemplo: drop table
#TRUNCATE - apagar  tudo da tabela e recria a tabela novamente:TRUNCATE TABLE TIMES

#COMANDOS DML INSERIR DADOS
INSERT INTO SERIES 
VALUES (1, 'SERIE A', 38, 261, 'SERIE DE ELITE' ); #OS DADOS PRECISAM SER INSERIDOS NA MESMA ORDEM QUE FORAM INDICADOS NA TABELA. NUMERICOS NÃO PRECISA DE ASPAS, CARACTERES COM ASPAS SIMPLES

INSERT INTO SERIES (ID, NOME, DESCRICAO)
VALUE (2, 'SERIE B', 'SERIE SECUNDARIA');

#COMANDOS DQL - CONSULTA
SELECT * FROM SERIES; #VISUALIZAR A TABELA
INSERT INTO TIMES 
VALUES (1,'PALMEIRAS','SAO PAULO', 'ABEL FERREIRA', 'ALIANZ PARK', 1);

INSERT INTO TIMES 
VALUES (2, 'BOTAFOGO', 'RIO DE JANEIRO', 'LUIS CASTRO', 'NILTON SANTOS', 1);

INSERT INTO TIMES
VALUES (3, 'FLUMINENSE', 'RIO DE JANEIRO', 'FERNANDO DINIZ', NULL, 1);

INSERT INTO TIMES
VALUES (4, 'CEARA', 'CEARÁ', 'LUCHO GONZALEZ', 'CASTELAO', 2);

INSERT INTO TIMES
VALUES ( 5, 'CORINTHIANS', 'SAO PAULO', 'LUXEMBURGO', 'NEOQUIMICA ARENA', 1);

INSERT INTO TIMES
VALUES (6, 'SPORT CLUB RECIFE', 'RECIFE', 'CLAUDINEI OLIVEIRA', 'ILHA DO RETIRO', 2);

SELECT * FROM TIMES;




